//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VimarCrm.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VimarCrm.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Accedi.
        /// </summary>
        internal static string Accedi {
            get {
                return ResourceManager.GetString("Accedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Evento giornaliero.
        /// </summary>
        internal static string AllDayEvent {
            get {
                return ResourceManager.GetString("AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ambito.
        /// </summary>
        internal static string Ambito {
            get {
                return ResourceManager.GetString("Ambito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        internal static string Annulla {
            get {
                return ResourceManager.GetString("Annulla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Appuntamento inserito correttamente.
        /// </summary>
        internal static string AppuntamentoInseritoCorrettamente {
            get {
                return ResourceManager.GetString("AppuntamentoInseritoCorrettamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione.
        /// </summary>
        internal static string Attenzione {
            get {
                return ResourceManager.GetString("Attenzione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cellulare.
        /// </summary>
        internal static string Cellulare {
            get {
                return ResourceManager.GetString("Cellulare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5 ore.
        /// </summary>
        internal static string CinqueOre {
            get {
                return ResourceManager.GetString("CinqueOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 5,5 ore.
        /// </summary>
        internal static string CinqueOreEMezza {
            get {
                return ResourceManager.GetString("CinqueOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cliente.
        /// </summary>
        internal static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Clienti.
        /// </summary>
        internal static string Clienti {
            get {
                return ResourceManager.GetString("Clienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice.
        /// </summary>
        internal static string Codice {
            get {
                return ResourceManager.GetString("Codice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice cliente.
        /// </summary>
        internal static string CodiceCliente {
            get {
                return ResourceManager.GetString("CodiceCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confermi il logout?.
        /// </summary>
        internal static string ConfermiLogout {
            get {
                return ResourceManager.GetString("ConfermiLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consuntivo.
        /// </summary>
        internal static string Consuntivo {
            get {
                return ResourceManager.GetString("Consuntivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contatti.
        /// </summary>
        internal static string Contatti {
            get {
                return ResourceManager.GetString("Contatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contatto.
        /// </summary>
        internal static string Contatto {
            get {
                return ResourceManager.GetString("Contatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contributi.
        /// </summary>
        internal static string Contributi {
            get {
                return ResourceManager.GetString("Contributi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cruscotto.
        /// </summary>
        internal static string Cruscotto {
            get {
                return ResourceManager.GetString("Cruscotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2 giorni.
        /// </summary>
        internal static string DueGiorni {
            get {
                return ResourceManager.GetString("DueGiorni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2 ore.
        /// </summary>
        internal static string DueOre {
            get {
                return ResourceManager.GetString("DueOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 2,5 ore.
        /// </summary>
        internal static string DueOreEMezza {
            get {
                return ResourceManager.GetString("DueOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata.
        /// </summary>
        internal static string Durata {
            get {
                return ResourceManager.GetString("Durata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Durata {0:%h} ore {0:%m} minuti.
        /// </summary>
        internal static string DurataFmt {
            get {
                return ResourceManager.GetString("DurataFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco clienti.
        /// </summary>
        internal static string ElencoClienti {
            get {
                return ResourceManager.GetString("ElencoClienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco contatti.
        /// </summary>
        internal static string ElencoContatti {
            get {
                return ResourceManager.GetString("ElencoContatti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco fatturati.
        /// </summary>
        internal static string ElencoFatturati {
            get {
                return ResourceManager.GetString("ElencoFatturati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EndPoint.
        /// </summary>
        internal static string EndPoint {
            get {
                return ResourceManager.GetString("EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fatturati OK / KO.
        /// </summary>
        internal static string FatturatiOkKo {
            get {
                return ResourceManager.GetString("FatturatiOkKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Fine.
        /// </summary>
        internal static string Fine {
            get {
                return ResourceManager.GetString("Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione contatto.
        /// </summary>
        internal static string GestioneContatto {
            get {
                return ResourceManager.GetString("GestioneContatto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione fatturato.
        /// </summary>
        internal static string GestioneFatturato {
            get {
                return ResourceManager.GetString("GestioneFatturato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestione lavoro.
        /// </summary>
        internal static string GestioneLavoro {
            get {
                return ResourceManager.GetString("GestioneLavoro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        internal static string Impostazioni {
            get {
                return ResourceManager.GetString("Impostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inizio.
        /// </summary>
        internal static string Inizio {
            get {
                return ResourceManager.GetString("Inizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invia a CAV.
        /// </summary>
        internal static string InviaACav {
            get {
                return ResourceManager.GetString("InviaACav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lavori.
        /// </summary>
        internal static string Lavori {
            get {
                return ResourceManager.GetString("Lavori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Località.
        /// </summary>
        internal static string Localita {
            get {
                return ResourceManager.GetString("Localita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luogo.
        /// </summary>
        internal static string Luogo {
            get {
                return ResourceManager.GetString("Luogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Menu clienti.
        /// </summary>
        internal static string MenuClienti {
            get {
                return ResourceManager.GetString("MenuClienti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 0,5 ore.
        /// </summary>
        internal static string Mezzora {
            get {
                return ResourceManager.GetString("Mezzora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo.
        /// </summary>
        internal static string Nuovo {
            get {
                return ResourceManager.GetString("Nuovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Obiettivo.
        /// </summary>
        internal static string Obiettivo {
            get {
                return ResourceManager.GetString("Obiettivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 8 ore.
        /// </summary>
        internal static string OttoOre {
            get {
                return ResourceManager.GetString("OttoOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Premi per chiudere.
        /// </summary>
        internal static string PremiPerChiudere {
            get {
                return ResourceManager.GetString("PremiPerChiudere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prossima visita.
        /// </summary>
        internal static string ProssimaVisita {
            get {
                return ResourceManager.GetString("ProssimaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 45 minuti.
        /// </summary>
        internal static string QuarantacinqueMinuti {
            get {
                return ResourceManager.GetString("QuarantacinqueMinuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 4 ore.
        /// </summary>
        internal static string QuattroOre {
            get {
                return ResourceManager.GetString("QuattroOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 4,5 ore.
        /// </summary>
        internal static string QuattroOreEMezza {
            get {
                return ResourceManager.GetString("QuattroOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 15 minuti.
        /// </summary>
        internal static string QuindiciMinuti {
            get {
                return ResourceManager.GetString("QuindiciMinuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ragione sociale.
        /// </summary>
        internal static string RagioneSociale {
            get {
                return ResourceManager.GetString("RagioneSociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Relazione.
        /// </summary>
        internal static string Relazione {
            get {
                return ResourceManager.GetString("Relazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca avanzata cliente.
        /// </summary>
        internal static string RicercaAvanzataCliente {
            get {
                return ResourceManager.GetString("RicercaAvanzataCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca cliente.
        /// </summary>
        internal static string RicercaCliente {
            get {
                return ResourceManager.GetString("RicercaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ruolo.
        /// </summary>
        internal static string Ruolo {
            get {
                return ResourceManager.GetString("Ruolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        internal static string Salva {
            get {
                return ResourceManager.GetString("Salva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 6 ore.
        /// </summary>
        internal static string SeiOre {
            get {
                return ResourceManager.GetString("SeiOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 6,5 ore.
        /// </summary>
        internal static string SeiOreEMezza {
            get {
                return ResourceManager.GetString("SeiOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare l&apos;ambito.
        /// </summary>
        internal static string SelezionareAmbito {
            get {
                return ResourceManager.GetString("SelezionareAmbito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare il cliente.
        /// </summary>
        internal static string SelezionareCliente {
            get {
                return ResourceManager.GetString("SelezionareCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare lo stato della visita.
        /// </summary>
        internal static string SelezionareStatoVisita {
            get {
                return ResourceManager.GetString("SelezionareStatoVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare la tipologia di visita.
        /// </summary>
        internal static string SelezionareTipologiaVisita {
            get {
                return ResourceManager.GetString("SelezionareTipologiaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 7 ore.
        /// </summary>
        internal static string SetteOre {
            get {
                return ResourceManager.GetString("SetteOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 7,5 ore.
        /// </summary>
        internal static string SetteOreEMezza {
            get {
                return ResourceManager.GetString("SetteOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si.
        /// </summary>
        internal static string Si {
            get {
                return ResourceManager.GetString("Si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stato visita.
        /// </summary>
        internal static string StatoVisita {
            get {
                return ResourceManager.GetString("StatoVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Telefono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipologia cliente.
        /// </summary>
        internal static string TipologiaCliente {
            get {
                return ResourceManager.GetString("TipologiaCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipologia visita.
        /// </summary>
        internal static string TipologiaVisita {
            get {
                return ResourceManager.GetString("TipologiaVisita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TO.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transfer.
        /// </summary>
        internal static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3 giorni.
        /// </summary>
        internal static string TreGiorni {
            get {
                return ResourceManager.GetString("TreGiorni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 30 minuti.
        /// </summary>
        internal static string TrentaMinuti {
            get {
                return ResourceManager.GetString("TrentaMinuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3 ore.
        /// </summary>
        internal static string TreOre {
            get {
                return ResourceManager.GetString("TreOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 3,5 ore.
        /// </summary>
        internal static string TreOreEMezza {
            get {
                return ResourceManager.GetString("TreOreEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1 giorno.
        /// </summary>
        internal static string UnGiorno {
            get {
                return ResourceManager.GetString("UnGiorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1 minuto.
        /// </summary>
        internal static string UnMinuto {
            get {
                return ResourceManager.GetString("UnMinuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1 ora.
        /// </summary>
        internal static string UnOra {
            get {
                return ResourceManager.GetString("UnOra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1,5 ore.
        /// </summary>
        internal static string UnOraEMezza {
            get {
                return ResourceManager.GetString("UnOraEMezza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utente.
        /// </summary>
        internal static string Utente {
            get {
                return ResourceManager.GetString("Utente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visite.
        /// </summary>
        internal static string Visite {
            get {
                return ResourceManager.GetString("Visite", resourceCulture);
            }
        }
    }
}
